### ISSUE TITLE
Search engines may display confusing text when searching for iced

### ISSUE THREAD

**Issue by eric-seppanen** [iced-rs/iced-rs.github.io#9]
I searched for iced on Google and the text that was included in the search page is highly misleading. It seems that the search engine is indexing the description of one of the showcase apps and treating it as the description of the entire iced.rs website.

![Screenshot from 2024-07-09 16-15-24](https://github.com/iced-rs/iced-rs.github.io/assets/109770420/7c442657-d7c1-4d58-a1fb-f421498b8d97)

**Comment by hecrj** [comment]
I added some `description` metadata to the `index.html`. Hopefully that helps.

**Comment by eric-seppanen** [comment]
I can confirm Google is displaying better text now.
